### ISSUE TITLE
[Suggestion] Recents Transparent Background

### ISSUE THREAD

**Issue by HeyItsJono** [KieronQuinn/PixelLauncherMods#49]
Hiya, thank you for the mods! Would it be possible to add an option to turn the solid colour background of the Recents view in Android 12 to transparent, since this seems to be controlled by the launcher? Lawnchair seems to offer this option but then I lose out on other Pixel Launcher exclusive features like extracting images/text from the Recents view.

**Comment by EleoXDA** [comment]
Ouch! Transparent recents looks hideous. Same as blur background. When you choose that option you have to make sure that the theme you chose is same as color of your wallpaper. Or else:
- when you have light colored wallpaper with dark theme you will get recents text (screenshot and select) as white text on white background.
- vice versa for dark theme with light colored wallpapet where you will get dark text on dark background.

To change recents text color you need to get more in depth and change the coloring mechanism of text in recents of Pixel Launcher and make sure it detects wallpaper color rather than theme color. Or else it will be a horror in your hands.

**Comment by HeyItsJono** [comment]
I think Lawnchair takes a nice approach in placing a partially transparent overlay of theme colour over the wallpaper so you get some transparency without compromising text readability. Would that be possible?

**Comment by EleoXDA** [comment]
The real question is:
- How much of your phone usage you are on QS or recents? 0.1% or 0.5%? Do you think it is worth all the hassle?

**Comment by EleoXDA** [comment]
Hi 
First things first, I am not the developer of this project.
I am just trying to ease up the work of developer by filtering out QA work. But as you said, KieronQuinn is the developer, and it is him to decide whether it is worth the time. My suggestion was, "do you think it will change you experience that much?". Because what you ask is not a function, but visual effect.

**Comment by HeyItsJono** [comment]
Yes it will change my experience. Just because a mod is visual rather than functional, doesn't make it worth immediately dismissing. That's the whole point of this mod letting you apply icon packs right?

**Comment by EleoXDA** [comment]
Icon packs can make you easily diagnose and even select custom icons for a set of apps that should work together or have similar function.

It can also help you recognize some apps that have poor iconic representations on their stock icon.

These all are improving functioning and user experience.

**Comment by Jnss98b** [comment]
Why are you being such a dick? @HeyItsJono posted a perfectly reasonable request. Just bc you're recruited to help with tech support doesn't mean you can just act all high and mighty and berate people. This isn't even the first time I've seen you act like a complete tool and reply in a passive and aggressive manner. Sure it's just a visual change but it's still perfectly reasonable, if not then no launcher would have implemented it in the first place. Whether or not you think it looks good or not doesn't matter, just don't enable it. Also, if the background is tinted or blurred well then contrast and visibility wouldn't be an issue at all. iOS has had blurred app switcher for almost a decade by now and Android has had a transparent one for even longer. Just relax.

**Comment by HeyItsJono** [comment]
> Why are you being such a dick? @HeyItsJono posted a perfectly reasonable request. Just bc you're recruited to help with tech support doesn't mean you can just act all high and mighty and berate people. This isn't even the first time I've seen you act like a complete tool and reply in a passive and aggressive manner. Sure it's just a visual change but it's still perfectly reasonable, if not then no launcher would have implemented it in the first place. Whether or not you think it looks good or not doesn't matter, just don't enable it. Also, if the background is tinted or blurred well then contrast and visibility wouldn't be an issue at all. iOS has had blurred app switcher for almost a decade by now and Android has had a transparent one for even longer. Just relax.

Thank you! I didn't want to say anything but this is pretty much how I felt lmao. I have no idea why someone who isn't even the developer of the project is being so gatekeepey and aggressive about this. I'd love to hear what @KieronQuinn thinks about the suggestion, if they don't think it's worth implementing then, again, I absolutely respect that.

**Comment by KieronQuinn** [comment]
> Just bc you're recruited to help with tech support doesn't mean you can just act all high and mighty and berate people. 

FWIW he is not recruited to do anything, no connection nor has he been asked to.

**Comment by Jnss98b** [comment]
> I am sorry that I answered your request even though I explicitly wrote that I am not the developer neither I have anything to do with development of this MOD. But from now on I will leave any posts or messages by HeyItsJono and Jnss98b unanswered because of your fowl language and not meeting [GitHub Code of Conduct](https://docs.github.com/en/site-policy/github-terms/github-event-code-of-conduct)
> 
> There was no reason to assault, harass or swear at me. But I will leave that to Admins of Github. I hope they can soon help me.
> 
> Bye

You "answered" but in a berating and power trippy way. Even though OP replied to you respectfully you still continued to act passive aggressively just because what they requested wasn't your preference. No one needs that energy in their life. Not to mention you inserted yourself and claimed you were asked to help with QA when that wasn't even the case. Oh and don't act like you're the victim now. I'd love for the admins of github to look over your comment history considering this isn't the first time I saw you act all high and mighty with people for perfectly reasonable questions. Heck, I even had the mis opportunity to deal with you directly many times before. All I did was calling out your shoddy behaviors. You thought you did something but not having you ruin my bug reports/feature requests is a blessing to me. Just remember that no matter how talented or good you are doesn't mean you can just tramp on people just because you think they're lesser than you

**Comment by Jnss98b** [comment]
Oh btw you linked the github **event** code of conduct page

**Comment by KieronQuinn** [comment]
Transparency slider added in 2.3

**Comment by Jnss98b** [comment]
Thank you so much!

**Comment by Jnss98b** [comment]
@KieronQuinn Do I need to do anything extra to get transparent recents bc it doesn't seem to work for me

https://user-images.githubusercontent.com/24306400/180106109-423e8770-394b-4a19-b09b-40218c6461fb.mp4

**Comment by KieronQuinn** [comment]
No, that should work. If it's not doing then there's nothing I can do. I can see the overlay is applying correctly in the video.

**Comment by Jnss98b** [comment]
Hmmm I'll have to play around with my magisk and lsposed modules to see if any of them is interfering

**Comment by Jnss98b** [comment]
Just a quick question, 0% is opaque and 100% is transparent for the slider right? @KieronQuinn

**Comment by KieronQuinn** [comment]
> Just a quick question, 0% is opaque and 100% is transparent for the slider right? @KieronQuinn

Correct

**Comment by HeyItsJono** [comment]
This is amazing, thank you so much for adding this! Working well for me after a restart on Android 12L on Pixel 5 via latest LSPosed/Magisk.

![Screenshot_20220721-114326](https://user-images.githubusercontent.com/4620093/180111690-da7bdd65-9f93-4cbe-a69f-bb61357ae517.png)

**Comment by Jnss98b** [comment]
I even downloaded the android 12 version they recommended too

**Comment by HeyItsJono** [comment]
On a Pixel 5 I use the MagiskHide Props Config module to set the following props:
```
Default boot stage (system.prop)
1 - ro.sf.blurs_are_expensive => set to 1
2 - ro.surface_flinger.supports_background_blur => set to 1

late_start service boot stage
3 - persist.sys.sf.disable_blurs => set to 0
```
Then reboot, go to Settings app -> System -> Developer Options and ensure "Allow Window-level Blurs" is enabled.

Next install the latest Magisk and LSPosed.

Then flash the latest ClearLineage zip obtained from their [telegram](https://t.me/clearlineage) and then reboot.

That's what worked for me. If you need help you can ask in their telegram or happy for you to drop your email and I can help you more there so we don't clutter up this Issues section.

**Comment by khaled-0** [comment]
Hey so this setting does nothing for me in android 13
The script runs successfully without errors but there's no effect.

**Comment by Jnss98b** [comment]
I have never been able to use it either lol. Must be cursed

**Comment by khaled-0** [comment]
Hey It just worked after installing the magisk module.
Weird it never prompted me to install it in that section.

**Comment by Jnss98b** [comment]
Wait what there's a magisk module??? Where did you find that lol

**Comment by khaled-0** [comment]
> Wait what there's a magisk module??? Where did you find that lol

Yes open the ``At a glance/Search Box`` in Tweaks and it'll ask you to save and install a module

**Comment by Jnss98b** [comment]
Ok my app is actually cursed then because it let me go through the whole process with the script running at the end without asking me to install the magisk module lol. And I checked magisk and there was not module there already. I'm gonna have to reset the app and check back. @KieronQuinn please add an option in settings to manually initiate installation of the magisk module so this wouldn't happen to other people

**Comment by KieronQuinn** [comment]
You have to do something to make the settings work without the module, like have a custom ROM installed with a broken form of the overlay included. This is why I tell people to not use those ROMs, and tell ROM makers to not include the overlay, but it's regularly ignored.

You can simply extract the magisk module from the APK, no need to manually initiate anything. It's all the UI does when 'saving' the module.

**Comment by Jnss98b** [comment]
I'm using the stock OS that comes installed with pixel though. Never used a custom rom in my life. Xposed is the furthest I've ever been in regards to android customization

**Comment by DragonFire1024** [comment]
> @HeyItsJono How did you get clearlineage to work on stock pixel rom? I tried to install it and got an error that it's not supported ![Screenshot_20220720-222741](https://user-images.githubusercontent.com/24306400/180117016-f21b151c-f70a-4f0c-ac9a-715409b27a78.png)

You have to manually add the module. In other words you have to manually create the folders and I had to actually install the clear lineage APK and then activate it through magisk but only after I had manually created the folders and directors inside /data/adb/modules. It didn't require a little bit of playing around with the applications in order to get them to work. In some cases I had to install the accent apks then install the APK through Magisk module folders then I had to go into settings, apps, select the accent APK, and then uninstall the updates through the top left corner clicking the triple dots. The only thing I can't get to work is is the recents being clear. I am on Android 12, stock firmware, Pixel 6 Pro.
![Screenshot_20240526-030744 1](https://github.com/KieronQuinn/PixelLauncherMods/assets/27289754/2b32155c-99fd-4275-901c-0692431092a6)
![Screenshot_20240526-030722 1](https://github.com/KieronQuinn/PixelLauncherMods/assets/27289754/5849e41b-1bb3-498e-8032-810f43bc5484)
![Screenshot_20240526-030754 1](https://github.com/KieronQuinn/PixelLauncherMods/assets/27289754/721f0cbb-bc0c-4fe6-86b2-d0bbf1e9aa9f)
![Screenshot_20240526-030810 1](https://github.com/KieronQuinn/PixelLauncherMods/assets/27289754/6fe01742-744b-43ec-a237-09a31cb8ac8c)
![Screenshot_20240526-031643 1](https://github.com/KieronQuinn/PixelLauncherMods/assets/27289754/53392d1c-5fde-4abd-9e42-009263e36bbc)
